DROP SCHEMA IF EXISTS BD_AUTOPSIAS;
CREATE SCHEMA BD_AUTOPSIAS;

DROP TABLE IF EXISTS BD_AUTOPSIAS.PERSONA;
DROP TABLE IF EXISTS BD_AUTOPSIAS.LEVANTAMIENTO;
DROP TABLE IF EXISTS BD_AUTOPSIAS.CASO;
DROP TABLE IF EXISTS BD_AUTOPSIAS.AUTOPSIA;
DROP TABLE IF EXISTS BD_AUTOPSIAS.HISTORIAL_CIRUGIA;
DROP TABLE IF EXISTS BD_AUTOPSIAS.PROCEDIMIENTOS;
DROP TABLE IF EXISTS BD_AUTOPSIAS.NACIONALIDAD;
DROP TABLE IF EXISTS BD_AUTOPSIAS.ANTECEDENTES_ENFERMEDADES;
DROP TABLE IF EXISTS BD_AUTOPSIAS.TRASTORNOS_Y_ENFERMEDADES;
DROP TABLE IF EXISTS BD_AUTOPSIAS.CAUSA_MUERTE_NATURAL;
DROP TABLE IF EXISTS BD_AUTOPSIAS.MUESTRAS;
DROP TABLE IF EXISTS BD_AUTOPSIAS.TIPO_MUESTRAS;
DROP TABLE IF EXISTS BD_AUTOPSIAS.FORENSE;
DROP TABLE IF EXISTS BD_AUTOPSIAS.CENTRO;
DROP TABLE IF EXISTS BD_AUTOPSIAS.PROVINCIA;
DROP TABLE IF EXISTS BD_AUTOPSIAS.JUZGADO;
DROP TABLE IF EXISTS BD_AUTOPSIAS.AREA_JUDICIAL;
DROP TABLE IF EXISTS BD_AUTOPSIAS.TOXICOS;
DROP TABLE IF EXISTS BD_AUTOPSIAS.TOXICOS_PERSONA;
DROP TABLE IF EXISTS BD_AUTOPSIAS.CAUSA_MUERTE_VIOLENTA;
DROP TABLE IF EXISTS BD_AUTOPSIAS.ORGANOS;
DROP TABLE IF EXISTS BD_AUTOPSIAS.ORGANOS_AUTOPSIA;
DROP TABLE IF EXISTS BD_AUTOPSIAS.ORGANOS_LESION;
DROP TABLE IF EXISTS BD_AUTOPSIAS.ARMAS;
DROP TABLE IF EXISTS BD_AUTOPSIAS.LESION;
DROP TABLE IF EXISTS BD_AUTOPSIAS.TIPO_LESION;
DROP TABLE IF EXISTS BD_AUTOPSIAS.LESION_HIMEN;
DROP TABLE IF EXISTS BD_AUTOPSIAS.IMAGEN;
DROP TABLE IF EXISTS BD_AUTOPSIAS.LESION_LOCALIZACION;
DROP TABLE IF EXISTS BD_AUTOPSIAS.LOCALIZACION;



CREATE TABLE BD_AUTOPSIAS.PERSONA (
	ID_PERSONA INT (11) NOT NULL,
	ID_NACIONALIDAD_ORIGEN INT (11) NOT NULL,
	ID_NACIONALIDAD INT (11) NOT NULL,
	NUSS INT (11) NOT NULL,
	DNI_NIE_PASAPORTE CHAR (12) NOT NULL,
	NOMBRE VARCHAR (30),
	APELLIDO_1 VARCHAR (30),
	APELLIDO_2 VARCHAR (30),
	FECHA_DE_NACIMIENTO DATE,
	FECHA_DE_FALLECIMIENTO DATE,
	EDAD INT (10),
	ALTURA INT (10),
	PESO INT (10),
	ESTADO_CIVIL CHAR (30),
	DIRECCION CHAR (30),
	CODIGO_POSTAL INT (11),
	SEXO CHAR(12),
	CONSTRAINT PK_PERSONA_ID_PERSONA PRIMARY KEY (ID_PERSONA),
	CONSTRAINT UQ_PERSONA_DNI_NIE_PASAPORTE UNIQUE (DNI_NIE_PASAPORTE)
);

CREATE TABLE BD_AUTOPSIAS.LEVANTAMIENTO (
	ID_LEVANTAMIENTO INT (11) NOT NULL,
	ID_PERSONA INT (11) NOT NULL,
	ID_FORENSE INT (11) NOT NULL,
	ID_PROVINCIA INT (11) NOT NULL,
	FECHA_DE_LEVANTAMIENTO DATETIME,
	DIRECCION VARCHAR (50),
	LUGAR_DE_OCURRENCIA CHAR (30),
	MUNICIPIO VARCHAR (50),
	CONSTRAINT PK_LEVANTAMIENTO_ID_LEVANTAMIENTO PRIMARY KEY (ID_LEVANTAMIENTO)
);

CREATE TABLE BD_AUTOPSIAS.CASO (
	ID_CASO INT (11) NOT NULL,
	EXPEDIENTE CHAR (11) NOT NULL,
	ID_JUZGADO INT (11) NOT NULL,
	LUGAR VARCHAR (100),
	FECHA_APERTURA DATE NOT NULL,
	CONSTRAINT PK_CASO_ID_CASO PRIMARY KEY (ID_CASO)
);

CREATE TABLE BD_AUTOPSIAS.AUTOPSIA (
	ID_AUTOPSIA INT (11) NOT NULL,
	ID_CASO INT (11) NOT NULL,
	ID_PERSONA INT (11) NOT NULL,
	ID_CENTRO INT (11) NOT NULL,
	ID_FORENSE INT (11) NOT NULL,
	CODIGO_AUTOPSIA INT (11) NOT NULL,
	NUMERO_HISTORIA INT (11) NOT NULL,
	ESTADO_ACTUAL CHAR (30),
	DILIGENCIA_INDETERMINADA BOOLEAN NOT NULL,
	SUBPERICIA_PATOLOGICA VARCHAR (100),
	ETIOLOGIA_MEDICO_LEGAL VARCHAR (100),
	FECHA_AUTOPSIA DATETIME,
	ASUNTO_GUARDIA BOOLEAN,
	VIOLENCIA_CONTRA_LA_MUJER BOOLEAN,
	VIOLENCIA_DOMESTICA BOOLEAN,
	CONSTRAINT PK_AUTOPSIA_ID_AUTOPSIA PRIMARY KEY (ID_AUTOPSIA)
);

CREATE TABLE BD_AUTOPSIAS.HISTORIAL_CIRUGIA (
	ID_HISTORIAL_CIRUGIA INT (11) NOT NULL,
	ID_PERSONA INT (11) NOT NULL,
	ID_PROCEDIMIENTO INT (11) NOT NULL,
	FECHA DATE,
	MOTIVO VARCHAR (30),
	CONSTRAINT PK_HISTORIAL_CIRUGIA_ID_HISTORIAL_CIRUGIA PRIMARY KEY (ID_HISTORIAL_CIRUGIA)
);

CREATE TABLE BD_AUTOPSIAS.PROCEDIMIENTOS (
	ID_PROCEDIMIENTO INT (11) NOT NULL,
	PROCEDIMIENTO VARCHAR (100) NOT NULL,
	AREA VARCHAR (100) NOT NULL,
	CONSTRAINT PK_PROCEDIMIENTOS_ID_PROCEDIMIENTO PRIMARY KEY (ID_PROCEDIMIENTO)
);

CREATE TABLE BD_AUTOPSIAS.NACIONALIDAD (
	ID_NACIONALIDAD INT (11) NOT NULL,
	PAIS VARCHAR (100) NOT NULL,
	CONSTRAINT PK_NACIONALIDAD_ID_NACIONALIDAD PRIMARY KEY (ID_NACIONALIDAD)
);

CREATE TABLE BD_AUTOPSIAS.ANTECEDENTES_ENFERMEDADES (
	ID_ANTECEDENTES_ENFERMEDADES INT (11) NOT NULL,
	ID_ENFERMEDAD CHAR (10) NOT NULL,
	ID_PERSONA INT (11) NOT NULL,
    FECHA_DIAGNOSTICO DATE,
    FECHA_ALTA DATE,
	TRATAMIENTO BOOLEAN NOT NULL,
	ESTADO VARCHAR (100) NOT NULL,
	NOMBRE_TRATAMIENTO VARCHAR (100),
	CONSTRAINT PK_ANTECEDENTES_ENFERMEDADES_ID_ANTECEDENTES_ENFERMEDADES PRIMARY KEY (ID_ANTECEDENTES_ENFERMEDADES)
);

CREATE TABLE BD_AUTOPSIAS.TRASTORNOS_Y_ENFERMEDADES (
	ID_ENFERMEDAD CHAR (10) NOT NULL,
	NOMBRE VARCHAR (100) NOT NULL,
	GRUPO VARCHAR (100) NOT NULL,
	CONSTRAINT PK_TRASTORNOS_ENFERMEDADES_ID_ENFERMEDAD PRIMARY KEY (ID_ENFERMEDAD)
);

CREATE TABLE BD_AUTOPSIAS.CAUSA_MUERTE_NATURAL (
	ID_CAUSA_MUERTE_NATURAL INT (11) NOT NULL,
	ID_ENFERMEDAD CHAR (10) NOT NULL,
	ID_AUTOPSIA INT (11) NOT NULL,
	ID_LESION INT (11) NOT NULL,
	INDICATIVO VARCHAR (100) NOT NULL,
	TIPO_MUERTE VARCHAR (100) NOT NULL,
	CONSTRAINT PK_CAUSA_MUERTE_NATURAL_ID_CAUSA_MUERTE_NATURAL PRIMARY KEY (ID_CAUSA_MUERTE_NATURAL)
);

CREATE TABLE BD_AUTOPSIAS.MUESTRAS(
	ID_MUESTRA INT (11) NOT NULL,
	ID_TIPO_MUESTRA INT (11) NOT NULL,
	ID_AUTOPSIA INT (11) NOT NULL,
	MUESTRA VARCHAR (100),
	FECHA_HORA DATETIME NOT NULL,
	CONSTRAINT PK_MUESTRAS_ID_MUESTRA PRIMARY KEY (ID_MUESTRA)
);

CREATE TABLE BD_AUTOPSIAS.TIPO_MUESTRAS(
	ID_TIPO_MUESTRA INT (11) NOT NULL,
	TIPO_MUESTRA VARCHAR (100),
	CONSTRAINT PK_TIPO_MUESTRAS_ID_TIPO_MUESTRA PRIMARY KEY (ID_TIPO_MUESTRA)
);

CREATE TABLE BD_AUTOPSIAS.FORENSE (
	ID_FORENSE INT (11) NOT NULL,
	NUMERO_COLEGIADO INT (11) NOT NULL,
	NOMBRE VARCHAR (100),
	APELLIDO_1 VARCHAR (100),
	APELLIDO_2 VARCHAR (100),
	ESPECIALIDAD VARCHAR (100),
	CONSTRAINT PK_FORENSE_ID_FORENSE PRIMARY KEY (ID_FORENSE)
);

CREATE TABLE BD_AUTOPSIAS.CENTRO (
	ID_CENTRO INT (11) NOT NULL,
	NOMBRE VARCHAR (100),
	TIPO_CENTRO VARCHAR (100),
	ID_PROVINCIA INT (2) NOT NULL,
	LOCALIDAD VARCHAR (100),
	DIRECCION VARCHAR (100),
	CONSTRAINT PK_CENTRO_ID_CENTRO PRIMARY KEY (ID_CENTRO)
);

CREATE TABLE BD_AUTOPSIAS.PROVINCIA (
	ID_PROVINCIA INT (2) NOT NULL,
	NOMBRE VARCHAR (100),
	CONSTRAINT PK_PROVINCIA_ID_PROVINCIA PRIMARY KEY (ID_PROVINCIA)
);

CREATE TABLE BD_AUTOPSIAS.JUZGADO (
	ID_JUZGADO INT (11) NOT NULL,
	ID_AREA_JUDICIAL INT (11) NOT NULL,
	NOMBRE VARCHAR (100),
	ID_PROVINCIA INT (2) NOT NULL,
	LOCALIDAD VARCHAR (100),
	DIRECCION VARCHAR (100),
	CONSTRAINT PK_JUZGADO_ID_JUZGADO PRIMARY KEY (ID_JUZGADO)
);

CREATE TABLE BD_AUTOPSIAS.AREA_JUDICIAL (
	ID_AREA_JUDICIAL INT (11) NOT NULL,
	NOMBRE VARCHAR (100),
	CONSTRAINT PK_AREA_JUDICIAL_ID_AREA_JUDICIAL PRIMARY KEY (ID_AREA_JUDICIAL)
);

CREATE TABLE BD_AUTOPSIAS.TOXICOS (
	ID_TOXICO INT (11) NOT NULL,
	NOMBRE VARCHAR (100),
	GRUPO_FARMACOLOGICO VARCHAR (1000),
	CONSTRAINT PK_TOXICOS_ID_TOXICO PRIMARY KEY (ID_TOXICO)
);

CREATE TABLE BD_AUTOPSIAS.TOXICOS_PERSONA (
	ID_TOXICO_PERSONA INT (11) NOT NULL,
	ID_TOXICO INT (11) NOT NULL,
	ID_PERSONA INT (11) NOT NULL,
	FRECUENCIA_CONSUMO VARCHAR (100) NOT NULL,
	CONSTRAINT PK_TOXICOS_PERSONA_ID_TOXICO_PERSONA PRIMARY KEY (ID_TOXICO_PERSONA)
);

CREATE TABLE BD_AUTOPSIAS.CAUSA_MUERTE_VIOLENTA (
	ID_CAUSA_MUERTE_VIOLENTA INT (11) NOT NULL,
	ID_TOXICO INT (11),
	ID_LESION INT (11),
	ID_AUTOPSIA INT (11) NOT NULL,
	TIPO_MUERTE VARCHAR (100) NOT NULL,
	CAUSA_MUERTE VARCHAR (100) NOT NULL,
	CONSTRAINT PK_CAUSA_MUERTE_VIOLENTA_ID_CAUSA_MUERTE_VIOLENTA PRIMARY KEY (ID_CAUSA_MUERTE_VIOLENTA)
);

CREATE TABLE BD_AUTOPSIAS.ARMA (
	ID_ARMA INT (11) NOT NULL,
	TIPO_ARMA VARCHAR (100),
	CONSTRAINT PK_ARMA_ID_ARMA PRIMARY KEY (ID_ARMA)
);

CREATE TABLE BD_AUTOPSIAS.LESION (
	ID_LESION INT (11) NOT NULL,
	ID_TIPO_LESION INT (11) NOT NULL,
	ID_AUTOPSIA INT (11) NOT NULL,
	ID_ARMA INT (11),
	DESCRIPCION VARCHAR (1000),
	GRAVEDAD VARCHAR (100),
	LESION_HIMEN BOOLEAN,
	CONSTRAINT PK_LESION_ID_LESION PRIMARY KEY (ID_LESION)
);

CREATE TABLE BD_AUTOPSIAS.TIPO_LESION (
	ID_TIPO_LESION INT (11) NOT NULL,
	TIPO_LESION VARCHAR (100),
	CONSTRAINT PK_LESION_ID_LESION PRIMARY KEY (ID_TIPO_LESION)
);

CREATE TABLE BD_AUTOPSIAS.LESION_HIMEN (
	ID_LESION INT (11) NOT NULL,
	TIPO_HIMEN VARCHAR (100),
	DILATACION VARCHAR (100),
	HERRAMIENTAS VARCHAR (100),
	LOCALIZACION_CARUNCULAS VARCHAR (100),
	TIPO_DESGARRO VARCHAR (100),
	DESCRIPCION VARCHAR (100),
	FECHA_DESGARRO DATETIME,
	FECHA_MUESCA DATETIME,
	CONSTRAINT PK_LESION_HIMEN_ID_LESION PRIMARY KEY (ID_LESION)
);

CREATE TABLE BD_AUTOPSIAS.IMAGEN (
	ID_IMAGEN INT (11) NOT NULL,
	ID_LESION INT (11) NOT NULL,
	URL VARCHAR (1000),
	CONSTRAINT PK_IMAGEN_ID_IMAGEN PRIMARY KEY (ID_IMAGEN)
);

CREATE TABLE BD_AUTOPSIAS.LESION_LOCALIZACION (
	ID_LESION_LOCALIZACION INT (11) NOT NULL,
	ID_LESION INT (11) NOT NULL,
	ID_LOCALIZACION INT (11) NOT NULL,
	COORDENADAS_X BIGINT,
	COORDENADAS_Y BIGINT,
	CONSTRAINT PK_LESION_LOCALIZACION_ID_LESION_LOCALIZACION PRIMARY KEY (ID_LESION_LOCALIZACION)
);

CREATE TABLE BD_AUTOPSIAS.LOCALIZACION (
	ID_LOCALIZACION INT (11) NOT NULL,
	VISTA VARCHAR (100) NOT NULL,
	AREA VARCHAR (100) NOT NULL,
	NOMBRE VARCHAR (100) NOT NULL,
	CONSTRAINT PK_LOCALIZACION_ID_LOCALIZACION PRIMARY KEY (ID_LOCALIZACION)
);

CREATE TABLE BD_AUTOPSIAS.ORGANOS_Y_HUESOS (
	ID_ORGANO_HUESO INT (11) NOT NULL,
	NOMBRE VARCHAR (30) NOT NULL,
	TIPO VARCHAR (30) NOT NULL,
	CONSTRAINT PK_ORGANOS_Y_HUESOS_ID_ORGANO_HUESO PRIMARY KEY (ID_ORGANO_HUESO)
);

CREATE TABLE BD_AUTOPSIAS.ORGANO_AUTOPSIA (
	ID_ORGANO_AUTOPSIA INT (11) NOT NULL,
	ID_AUTOPSIA INT(11) NOT NULL,
	ID_ORGANO INT(11) NOT NULL,
	PESO INT (10),
	CONSTRAINT PK_ORGANO_AUTOPSIA_ID_ORGANO_AUTOPSIA PRIMARY KEY (ID_ORGANO_AUTOPSIA)
);

CREATE TABLE BD_AUTOPSIAS.ORGANO_LESION (
	ID_ORGANO_LESION INT (11) NOT NULL,
	ID_ORGANO_AUTOPSIA INT (11) NOT NULL,
	ID_LESION INT (11) NOT NULL,
	ESTADO VARCHAR (30),
	CONSTRAINT PK_ORGANO_LESION_ID_ORGANO_LESION PRIMARY KEY (ID_ORGANO_LESION)
);

ALTER TABLE BD_AUTOPSIAS.PERSONA
ADD  CONSTRAINT FK_NACIONALIDAD_DE_ORIGEN_ID_NACIONALIDAD
    FOREIGN KEY(ID_NACIONALIDAD_ORIGEN)
	REFERENCES BD_AUTOPSIAS.NACIONALIDAD (ID_NACIONALIDAD)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_NACIONALIDAD_ID_NACIONALIDAD
    FOREIGN KEY(ID_NACIONALIDAD)
	REFERENCES BD_AUTOPSIAS.NACIONALIDAD (ID_NACIONALIDAD)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE BD_AUTOPSIAS.LEVANTAMIENTO
ADD  CONSTRAINT FK_LEVANTAMIENTO_ID_PERSONA
    FOREIGN KEY(ID_PERSONA)
	REFERENCES BD_AUTOPSIAS.PERSONA (ID_PERSONA)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_LEVANTAMIENTO_ID_FORENSE
    FOREIGN KEY(ID_FORENSE)
	REFERENCES BD_AUTOPSIAS.FORENSE (ID_FORENSE)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_LEVANTAMIENTO_ID_PROVINCIA
    FOREIGN KEY(ID_PROVINCIA)
	REFERENCES BD_AUTOPSIAS.PROVINCIA (ID_PROVINCIA)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE BD_AUTOPSIAS.AUTOPSIA
ADD  CONSTRAINT FK_AUTOPSIA_ID_CASO
    FOREIGN KEY(ID_CASO)
	REFERENCES BD_AUTOPSIAS.CASO (ID_CASO)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD CONSTRAINT FK_AUTOPSIA_ID_CENTRO
	FOREIGN KEY(ID_CENTRO)
	REFERENCES BD_AUTOPSIAS.CENTRO (ID_CENTRO)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_AUTOPSIA_ID_PERSONA
    FOREIGN KEY(ID_PERSONA)
	REFERENCES BD_AUTOPSIAS.PERSONA (ID_PERSONA)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_AUTOPSIA_ID_FORENSE
    FOREIGN KEY(ID_FORENSE)
	REFERENCES BD_AUTOPSIAS.FORENSE (ID_FORENSE)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE BD_AUTOPSIAS.CASO
ADD  CONSTRAINT FK_CASO_ID_JUZGADO
    FOREIGN KEY(ID_JUZGADO)
	REFERENCES BD_AUTOPSIAS.JUZGADO (ID_JUZGADO)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE BD_AUTOPSIAS.HISTORIAL_CIRUGIA
ADD  CONSTRAINT FK_HISTORIAL_CIRUGIA_ID_PERSONA
    FOREIGN KEY(ID_PERSONA)
	REFERENCES BD_AUTOPSIAS.PERSONA (ID_PERSONA)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_HISTORIAL_CIRUGIA_ID_PROCEDIMIENTOS
    FOREIGN KEY(ID_PROCEDIMIENTO)
	REFERENCES BD_AUTOPSIAS.PROCEDIMIENTOS (ID_PROCEDIMIENTO)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
	
ALTER TABLE BD_AUTOPSIAS.ANTECEDENTES_ENFERMEDADES
ADD  CONSTRAINT FK_ANTECEDENTES_ENFERMEDADES_ID_PERSONA
    FOREIGN KEY(ID_PERSONA)
	REFERENCES BD_AUTOPSIAS.PERSONA (ID_PERSONA)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_ANTECEDENTES_ENFERMEDADES_ID_ENFERMEDAD
    FOREIGN KEY(ID_ENFERMEDAD)
	REFERENCES BD_AUTOPSIAS.TRASTORNOS_Y_ENFERMEDADES (ID_ENFERMEDAD)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
	
ALTER TABLE BD_AUTOPSIAS.CAUSA_MUERTE_NATURAL
ADD  CONSTRAINT FK_CAUSA_MUERTE_NATURAL_ID_AUTOPSIA
    FOREIGN KEY(ID_AUTOPSIA)
	REFERENCES BD_AUTOPSIAS.AUTOPSIA (ID_AUTOPSIA)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_CAUSA_MUERTE_NATURAL_ID_ENFERMEDAD
    FOREIGN KEY(ID_ENFERMEDAD)
	REFERENCES BD_AUTOPSIAS.TRASTORNOS_Y_ENFERMEDADES (ID_ENFERMEDAD)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_CAUSA_MUERTE_NATURAL_ID_LESION
    FOREIGN KEY(ID_LESION)
	REFERENCES BD_AUTOPSIAS.LESION (ID_LESION)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
	
ALTER TABLE BD_AUTOPSIAS.CAUSA_MUERTE_VIOLENTA
ADD  CONSTRAINT FK_CAUSA_MUERTE_VIOLENTA_ID_AUTOPSIA
    FOREIGN KEY(ID_AUTOPSIA)
	REFERENCES BD_AUTOPSIAS.AUTOPSIA (ID_AUTOPSIA)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_CAUSA_MUERTE_VIOLENTA_ID_TOXICO
    FOREIGN KEY(ID_TOXICO)
	REFERENCES BD_AUTOPSIAS.TOXICOS (ID_TOXICO)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_CAUSA_MUERTE_VIOLENTA_ID_LESION
    FOREIGN KEY(ID_LESION)
	REFERENCES BD_AUTOPSIAS.LESION (ID_LESION)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE BD_AUTOPSIAS.TOXICOS_PERSONA
ADD  CONSTRAINT FK_TOXICOS_PERSONA_ID_PERSONA
    FOREIGN KEY(ID_PERSONA)
	REFERENCES BD_AUTOPSIAS.PERSONA (ID_PERSONA)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_TOXICOS_PERSONA_ID_TOXICO
    FOREIGN KEY(ID_TOXICO)
	REFERENCES BD_AUTOPSIAS.TOXICOS (ID_TOXICO)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
	
ALTER TABLE BD_AUTOPSIAS.MUESTRAS
ADD  CONSTRAINT FK_MUESTRAS_ID_TIPO_MUESTRAS
    FOREIGN KEY(ID_TIPO_MUESTRA)
	REFERENCES BD_AUTOPSIAS.TIPO_MUESTRAS (ID_TIPO_MUESTRA)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_MUESTRAS_ID_AUTOPSIA
    FOREIGN KEY(ID_AUTOPSIA)
	REFERENCES BD_AUTOPSIAS.AUTOPSIA (ID_AUTOPSIA)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE BD_AUTOPSIAS.CENTRO
ADD  CONSTRAINT FK_CENTRO_ID_PROVINCIA
    FOREIGN KEY(ID_PROVINCIA)
	REFERENCES BD_AUTOPSIAS.PROVINCIA (ID_PROVINCIA)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE BD_AUTOPSIAS.JUZGADO
ADD  CONSTRAINT FK_JUZGADO_ID_AREA_JUDICIAL
    FOREIGN KEY(ID_AREA_JUDICIAL)
	REFERENCES BD_AUTOPSIAS.AREA_JUDICIAL (ID_AREA_JUDICIAL)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_JUZGADO_ID_PROVINCIA
    FOREIGN KEY(ID_PROVINCIA)
	REFERENCES BD_AUTOPSIAS.PROVINCIA (ID_PROVINCIA)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
	
ALTER TABLE BD_AUTOPSIAS.LESION
ADD  CONSTRAINT FK_LESION_ID_TIPO_LESION
    FOREIGN KEY(ID_TIPO_LESION)
	REFERENCES BD_AUTOPSIAS.TIPO_LESION (ID_TIPO_LESION)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_LESION_ID_AUTOPSIA
    FOREIGN KEY(ID_AUTOPSIA)
	REFERENCES BD_AUTOPSIAS.AUTOPSIA (ID_AUTOPSIA)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_LESION_ID_ARMA
    FOREIGN KEY(ID_ARMA)
	REFERENCES BD_AUTOPSIAS.ARMA (ID_ARMA)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
	
ALTER TABLE BD_AUTOPSIAS.LESION_HIMEN
ADD  CONSTRAINT FK_LESION_HIMEN_ID_LESION
    FOREIGN KEY(ID_LESION)
	REFERENCES BD_AUTOPSIAS.LESION (ID_LESION)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
	
ALTER TABLE BD_AUTOPSIAS.IMAGEN
ADD  CONSTRAINT FK_IMAGEN_ID_LESION
    FOREIGN KEY(ID_LESION)
	REFERENCES BD_AUTOPSIAS.LESION (ID_LESION)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
	
ALTER TABLE BD_AUTOPSIAS.LESION_LOCALIZACION
ADD  CONSTRAINT FK_LESION_LOCALIZACION_ID_LESION
    FOREIGN KEY(ID_LESION)
	REFERENCES BD_AUTOPSIAS.LESION (ID_LESION)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_LESION_LOCALIZACION_ID_LOCALIZACION
    FOREIGN KEY(ID_LOCALIZACION)
	REFERENCES BD_AUTOPSIAS.LOCALIZACION (ID_LOCALIZACION)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
	
ALTER TABLE BD_AUTOPSIAS.ORGANO_AUTOPSIA
ADD  CONSTRAINT FK_ORGANO_AUTOPSIA_ID_AUTOPSIA
    FOREIGN KEY(ID_AUTOPSIA)
	REFERENCES BD_AUTOPSIAS.AUTOPSIA (ID_AUTOPSIA)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_ORGANO_AUTOPSIA_ID_ORGANO_HUESO
    FOREIGN KEY(ID_ORGANO)
	REFERENCES BD_AUTOPSIAS.ORGANOS_Y_HUESOS (ID_ORGANO_HUESO)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
	
ALTER TABLE BD_AUTOPSIAS.ORGANO_LESION
ADD  CONSTRAINT FK_ORGANO_LESION_ID_LESION
    FOREIGN KEY(ID_LESION)
	REFERENCES BD_AUTOPSIAS.LESION (ID_LESION)
	ON UPDATE RESTRICT ON DELETE RESTRICT,
ADD  CONSTRAINT FK_ORGANO_LESION_ID_ORGANO_AUTOPSIA
    FOREIGN KEY(ID_ORGANO_AUTOPSIA)
	REFERENCES BD_AUTOPSIAS.ORGANO_AUTOPSIA (ID_ORGANO_AUTOPSIA)
	ON UPDATE RESTRICT ON DELETE RESTRICT;